### ISSUE TITLE
Feature Request: add a flag to `moni mems` to get SAM format output

### ISSUE THREAD

**Issue by AndreaGuarracino** [maxrossi91/moni#10]
Hi, would it be possible to add a flag to `moni mems` (something like `-f/--format sam`) to get the MEMs in SAM format? I see you've recently added

```
  -e, --extended-output
                        output MEM occurrence in the reference (default: False)
```

so it sounds like something doable.

**Comment by maxrossi91** [comment]
This shouldn't be too difficult. However, I don't know when I have time to implement this though.

**Comment by maxrossi91** [comment]
Well, thinking about it a little bit more, it is not that simple. What the output format would look like? You will have 1 row per MEM, marked as secondary alignment (except the first one) and a CIGAR with either a soft or hard clip on either side of the MEM, and the MEM reported as M.

As `moni mem` is structured right not this might be not as easy, since it would require to change the encoding of the intermediate files in the case of SAM output to carry over both the sequence and the base quality of the reads.

I need to think a little bit more about it.

**Comment by AndreaGuarracino** [comment]
Would the PAF format be easier?
________________________________

**Comment by maxrossi91** [comment]
Yeah, maybe PAF would have been easier. Less cluttered output avoiding redundant SEQ and BASE QUALs.

I have implemented a quick feature. Please give it a try.

**Comment by AndreaGuarracino** [comment]
Thx a lot! Could you please make a pre-built binary? I still can't compile MONI.

About the PAF format, it would allow a very light output compared to SAM format output. We are interested in applying MONI on huge pangenomes, so a PAF output would be helpful. If I were able to compile the source, I would be able to work on that.

________________________________

**Comment by maxrossi91** [comment]
I made a full release and bumped the version to `v0.2.2`. 

Re: compilation. I am able to compile using gcc 9.3.0, please try that and see if that works for you. 

I agree PAF format might be lighter, and probably easier to implement. Unfortunately the `moni mems` code is quite messy and it might use some refactoring at this point, however the time is not much to dedicate to it on my spare time. 

Happy to take PRs if you want to give it a try.

Closing this issue for now. Let me open another feature request for the PAF format.
